name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  godot-ci:
    name: Godot CI
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates/
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      env:
        GODOT_VERSION: 4.3
    
    - name: Verify Project
      run: |
        godot --headless --verbose --check-only --path . --quit
    
    - name: Import Resources
      run: |
        godot --headless --verbose --editor --path . --quit
    
    - name: Test Web Export
      run: |
        mkdir -v -p build/web
        godot --headless --verbose --export-release "Web" build/web/index.html --path .
    
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web
        retention-days: 14

  lint-scripts:
    name: Lint GDScript
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Lint GDScript files
      run: |
        find . -name "*.gd" -exec godot --headless --script-validate {} \;
